#!/usr/bin/env bash

set -e -x

DOTBOT_BIN="bin/dotbot"
DOTBOT_CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot/dotbot"
DOTBOT_PLUGINS=""

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
python3 -B "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
    --base-directory "${BASEDIR}"                   \
    --config-file "${DOTBOT_CONFIG}"                \
    ${DOTBOT_PLUGINS}                               \
    -vv                                             \
    "${@}"
