# GDM configuration storage
#
# See /usr/share/gdm/gdm.schemas for a list of available options.

[daemon]
AutomaticLoginEnable=True
AutomaticLogin=ajaysriv
# WaylandEnable=false

[debug]
# Enable=true
